#!/usr/bin/sh

#set -xe

# xrandr --output eDP-1-1 --auto

displays=($(xrandr | grep -i -e '\bconnected\b' | awk '{printf ("%s\n",$1) }' | sort))
bspc_monitors=$(bspc query -M)

echo $displays
echo $bspc_monitors

if [[ ${#displays[@]} = 2 ]]; then
	echo "Two monitors"
    # xrandr --output ${displays[1]} --left-of ${displays[0]}
    bspc monitor ${displays[1]} -d 1 2 3 4 5
    bspc monitor ${displays[0]} -d 6 7 8 9 10
else
	echo "One monitor"
    # xrandr --output ${displays[0]} --auto
    bspc monitor ${displays[0]} -d 1 2 3 4 5 6 7 8 9 10
fi

wmname LG3D

# killall sxhkd; sxhkd &

$HOME/.config/polybar/launch.sh &

#urxvt256c-ml &

#bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-0 -d 1 2 3 4 5
#bspc monitor eDP-1-1 -d 6 7 8 9 10
#for monitor in $(bspc query -M); do
#    bspc monitor $monitor -d 1 2 3 4
#done


# Border colors
bspc config normal_border_color "#484848"
bspc config active_border_color "#7777AA"
bspc config focused_border_color "#AA7777"
bspc config urgent_border_color "#B58900"
bspc config presel_feedback_color "#26E2FF"

bspc config click_to_focus any

bspc config honor_size_hints false

bspc config ignore_ewmh_focus true
bspc config ignore_ewmh_fullscreen true

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         0
bspc config bottom_padding      30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme     alternate
bspc config single_monocle     false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a Firefox desktop='2'
bspc rule -a firefox desktop='2'
bspc rule -a Rambox desktop='9'
bspc rule -a Sublime_text desktop='1'
bspc rule -a Code desktop='1'
bspc rule -a jetbrains-idea-ce desktop='1'
bspc rule -a jetbrains-idea desktop='1'
bspc rule -a jetbrains-clion desktop='1'
bspc rule -a jetbrains-phpstorm desktop='1'
bspc rule -a jetbrains-goland desktop='1'
bspc rule -a Postman desktop='4'
bspc rule -a jetbrains-pycharm desktop='1'
bspc rule -a 'MATLAB R2015a' desktop='3'
# bspc rule -a 'Spotify' desktop='7'
# bspc rule -a 'spotify' desktop='7'

bspc rule -a Nautilus state=floating
bspc rule -a KeePassXC state=floating
bspc rule -a keepassxc state=floating
bspc rule -a Gcr-viewer state=floating
#bspc rule -a copyq state=floating
bspc rule -a Zathura state=tiled
bspc rule -a 'jetbrains-toolbox' state=floating

bspc config external_rules_command ~/repos/dotfiles/desktop/bspwm/external_rules

killall bspc
#sh -c 'bspc subscribe | while read; do bash /home/sandim/.config/bspwm/titlebars.sh ; done' &

#killall copyq; copyq &

nm-applet &
lxpolkit &
#dropbox start &
maestral start &
rambox &
xautolock -time 15 -locker 'i3lock -i /tmp/wallpaper.png -c 222222' &
killall clipster; clipster -d
# dunst &
