#! /bin/sh

wid=$1
class=$(echo "$2" | tr '[:upper:]' '[:lower:]')
instance=$3
consequences=$4
title=$(xtitle "$wid")

# echo "$wid - $class - $instance - $title - $consequences" >> /tmp/ruleslog.log

case "$class" in
  firefox)
    if [ "$title" = "Picture-in-Picture" ] ; then
      echo "state=floating"
    fi
    ;;
  qalculate-gtk|"toggl desktop")
    echo "state=floating"
    ;;
  slack)
    # echo "slack - #$title#" >> /tmp/ruleslog.log
    echo "desktop=0"
    if [ "$title" = "Slack | mini panel" ] ; then
      # echo "hidden=on" >> /tmp/ruleslog.log
      echo "hidden=on"
    fi
    ;;
  '')
    case "$title" in
      "Spotify")
        echo "desktop=7"
        ;;
    esac
    ;;
esac
